server:
  port: 8081  # Port number for the auth-service

spring:
  application:
    name: auth-service  # Name of the microservice
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth-service

jwt:
  secret: myjwtsecretkey
  expiration: 3600

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

# Custom security configurations (optional)
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html