server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  dashboard:
    enabled: true

spring:
  application:
    name: eureka-server

logging:
  level:
    org.springframework: INFO

